### ISSUE TITLE
Enable ActiveLogin.Authentication to be used without the built in GUI

### ISSUE THREAD

**Issue by FredrikK** [ActiveLogin/ActiveLogin.Authentication#122]
**Is your feature request related to a problem? Please describe.**
If you want to use `ActiveLogin.Authentication.BankId` without the built in GUI in `ActiveLogin.Authentication.BankId.AspNetCore` it is not possible since a lot of functionality is currently placed in `ActiveLogin.Authentication.BankId.AspNetCore`.
It's a show stopper if you want to build a REST service with `ActiveLogin.Authentication.BankId` without using the:
```csharp
services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie()
                .AddBankId(...)
```

**What area is it related to**
BankID, API

**Describe the solution you'd like**
To pull out common functionality from `ActiveLogin.Authentication.BankId.AspNetCore` into a new project. Suggestions:
- `ActiveLogin.Authentication.BankId.Common`
- `ActiveLogin.Authentication.BankId`
- `ActiveLogin.Authentication.Common` 

**Describe alternatives you've considered**
Copy/pasting from `ActiveLogin.Authentication.BankId.AspNetCore` into our project and just use the `ActiveLogin.Authentication.BankId.Api` package

**Additional context**
We will add areas that need to be moved soon...

**Comment by PeterOrneholm** [comment]
Thank you for the suggestion @FredrikK!

I agree this could be beneficial if done right. The downside is that at the moment some of these things are "implementation" details and we can make changes without introducing breaking changes, therefore we need to be careful on what things are exposed publicly as we'll have to live with those for some time.

A few questions:

1. The reason for doing this, is that you don't want to use the UI. Are you able to share why that is? Do you have an existing implementation that you want to keep? We would like to make the UI part as good and customization as possible so that you don't have to build it yourself. One reason I can see myself now is that if you want to use it from "old" ASP.NET (as I know we have cases for).

2. `ActiveLogin.Authentication.BankId.Common` would be where I put my vote on at the moment. As far as I know we don't have to much in common between BankID/GrandID and don't want to create a to big of common package.

3. Could you provide a more detailed list of suggested functionality that should be moved into a common package. Please also provide a "pitch" for those cases. As described above, exposing this functionality comes with some side effects, so each feature moved with a public API needs to be thought through.

**Comment by PeterOrneholm** [comment]
Hi again @FredrikK! Any additional input on this? We are getting closer to release 3.0.0 of our package, and that would be a good time to include this as it might be a breaking change.

No stress, we could plan it for a 4.0.0 release as well.

**Comment by PeterOrneholm** [comment]
Still interested in this @FredrikK? We wither need to know the needs, as described above, or we'll close it for now.

**Comment by FredrikK** [comment]
Hi @PeterOrneholm, sorry for the late reply.
Unfortunately we had to proceed without ActiveLogin.Authentication but the idea still stands (in my opinion) so I will try and answer the questions above.

1. We have a lot of business and regulatory rules to have a very custom login web with several auth methods. We also have a few other web pages that need access to the BankID api. So our idea is to make a custom BankID.Rp rest-service that is a "proxy" to api.bankid.com with extra rules. 

2. Sounds great. I hate the namespace "Common", but i wrote it first :-(

3. I think we ended up with config and certificate-classes

**Comment by PeterOrneholm** [comment]
Thanks for input!

> 1. We have a lot of business and regulatory rules to have a very custom login web with several auth methods. We also have a few other web pages that need access to the BankID api. So our idea is to make a custom BankID.Rp rest-service that is a "proxy" to api.bankid.com with extra rules.

I see, at the moment the API wrapper is a separate package. Could you use that in any way?

> 2. Sounds great. I hate the namespace "Common", but i wrote it first :-(

I've given it some thoughts, and looked at other packages. "Core" seems to be a better name.
`ActiveLogin.Authentication.BankId.Core`

And if we have common stuff that's not only relevant for BankID:

`ActiveLogin.Authentication.Core`

> 3. I think we ended up with config and certificate-classes

Ok, I see. So basically configuring the HttpClient when using the Api wrapper only?


I think this is a good direction to go to, but would like to wait it out until we have a good description on how and exactly for what it should be used, so we make the best out of it. Will close it for now, but can reopen again when we have more usecases :)
