### ISSUE TITLE
QR code authentication message flickers and could be clarified

### ISSUE THREAD

**Issue by span** [ActiveLogin/ActiveLogin.Authentication#188]
**Describe the bug**
When the user authenticates using QR code an initial message "Trying to start your BankID app" is displayed. Then it is replaced as the first transaction comes back. The message that replaces the first message, "Start your BankID app.", could be improved to assist the user on how to scan the QR code.

**What area is it related to**
BankID

**To Reproduce**
1. Start authentication session with QR code

**Expected behavior**
Short and obvious information displayed to the user

**NuGet package version**
Latest master

**Runtime version**
.net core 3.1

**Additional context**
Although the Relying Party Guidelines does not contain an obvious recommendation to the user on how to authenticate using QR codes I belive that a slightly changed message from the recommended message can greatly improve the UX.

I also find it strange to see the flickering initial message. Perhaps it can be completely removed.

**Comment by PeterOrneholm** [comment]
I agree, we should fix this!

While on it, we should fix another thing. It's so closely related so I won't open a separate issue for it.

It's related to when we change the QR-code every 20 seconds. It's implemented in a way so that when the client receives that it should make another try, it calls `login()` which will call `initialize()` and `initialize` till reset the sate, and therefore hide the QR code image for a brief moment. It's perceived as the site "jumps". It should be an easy fox not to hide the QR code on reinit if we expect a new QR image.

**Comment by PeterOrneholm** [comment]
I've started an implementation in #195.
Still need to fix the message when QR:

Can you have a first quick look @span?
