### ISSUE TITLE
Does ActiveLogin support Mobile Integration with GrandId API?

### ISSUE THREAD

**Issue by axelspangberg** [ActiveLogin/ActiveLogin.Authentication#217]
**Is your feature request related to a problem? Please describe.**
I want to register multiple ServiceKeys (BankID v3 for apps) in project startup to support BankId integrations using mobile apps. https://docs.grandid.com/mobileintegrations

**What area is it related to**
GrandID API

**Describe the solution you'd like**
Is it possible to register multiple servicekeys using activelogin in .AddGrandId(builder =>[...]).?

These are the servicekeys i want to register:

- serviceKey (BankID v3 for apps)
- serviceKey (BankID v3 auth Same device)
- serviceKey (BankID v3 auth Other device)

**Additional context**
Maybe im missing something, if so - please close this suggestion.

**Comment by PeterOrneholm** [comment]
Hi Axel!

> Is it possible to register multiple servicekeys using activelogin in .AddGrandId(builder =>[...]).?

Using the "low level" API (`ActiveLogin.Authentication.GrandId.Api`) it is, that is just a wrapper around their JSON API. But that leaves it to you to implement the authentication flow on top of that.

When using the ASP.NET Core Authentication module (`ActiveLogin.Authentication.GrandId.AspNetCore`) you are only supposed to use one of the keys, probably the "app" key in your case. We do have a note on this [in our documentation](https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/docs/getting-started-grandid-bankid.md#preparation). It requires you to have been upgraded to the latest version, as that is the only version we do support.

Then you can register multiple schemas using that key, and _Same device_ vs _Other device_ is instead set through parameters. See our sample here:
https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/samples/IdentityServer.ServerSample/Startup.cs#L136

As per my understanding, the [Mobile integrations](https://docs.grandid.com/mobileintegrations) is rather a guide on how to use the same setup, but in a mobile scenario. The most important thing is that the mobile can't call the GrandID right away, but need to go through your API (which could be Active Login + Identity Server). Otherwise you would expose your secret keys in the app.

Hope this helps :)

**Comment by PeterOrneholm** [comment]
Did this help you out @axelspangberg? I'll close the issue for now, but can open it again if you have any further questions.
