### ISSUE TITLE
_LoginScript.cshtml JS data object keys should be in upper case

### ISSUE THREAD

**Issue by staslebedenko** [ActiveLogin/ActiveLogin.Authentication#232]
**Describe the bug**
_LoginScript.cshtml Javascript data object keys are upper case. But object keys in code are lowercase. Conditions like (data.isAutoLaunch) should be in upper case (data.IsAutoLaunch).

https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/744e9b236ae23e9d63f7c49ff672b676a88efa1c/src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/_LoginScript.cshtml#L105

**What area is it related to**
BankID

**To Reproduce**
1. Open Identity Server sample and add custom views from
https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/master/src/ActiveLogin.Authentication.BankId.AspNetCore/Areas/BankIdAuthentication/Views/BankId/
2. Go to '_LoginScript.cshtml'
3. Add 'debugger;' before line 105 
4. Launch Identity server sample with any config.
5. Open Chrome dev tools and start authentication process 
6. Compare line 106 data.isAutoLaunch is undefined data data.IsAutoLaunch is true or false.

**Expected behavior**
JS data object keys in file should be in upper case.

**Screenshots**
![image](https://user-images.githubusercontent.com/36765741/80585363-e04b4200-8a1b-11ea-92be-68ca0d30814e.png)

**NuGet package version**
3.0.0

**Runtime version**
netcoreapp3.1

**Desktop (please complete the following information):**
 - Windows 10 
 - Edge chromium , Chrome
 - Version 81

**Additional context**
Not sure about views in a NuGet package, because I`m using customized ones.
I can create a pull request with this minor fixes.

**Comment by PeterOrneholm** [comment]
Hi @staslebedenko and thank you for the detailed issue!
I was so sure we had tested this (manually) and I can confirm that the properties from the server are camelCased by default, for example, try our demo site (deployed with latest from master):
https://al-samples-identityserver.azurewebsites.net/

![image](https://user-images.githubusercontent.com/1662918/80680205-9c5d4900-8abe-11ea-8f82-26c3dc499b3d.png)

Since (I think it was) ASP.NET Core 2.0 if you return JSON from ASP.NET Core it will be formatted using camelCase, and we seem to rely on that. If you (for some reason) change back to the old behavior using (for example) `UseCamelCasing` (https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.mvcjsonoptionsextensions.usecamelcasing?view=aspnetcore-2.2) you are correct it won't work.

Can you confirm that you have overridden this setting in any way? There might be other ways than UseCamelCasing.

Anyway, it's not good we relay n this behavior. I'd suggest that we investigate if we from our endpoint can return the JSON more explicitly in the format we want, not inheriting the settings from the global formatter. A quick "googling" says we can do so, look at "per-action" formatting here:
https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.1#configure-systemtextjson-based-formatters

Fell free to make a PR with such change, or we'll find time to do it later. For now, this issue is a good description of what to do until this fix is done.

**Comment by staslebedenko** [comment]
Hi @PeterOrneholm .

Thanks for the heads-up. Yes it was a configuration issue on my side, connected with other functionality. Completely missed this out.

![image](https://user-images.githubusercontent.com/36765741/80995702-5cdc8700-8e47-11ea-9ce1-3a904138f7e4.png)

I will look into the custom formatter for camelCase and prepare a PR this week :).

**Comment by PeterOrneholm** [comment]
> I will look into the custom formatter for camelCase and prepare a PR this week :).

Awesome :)
