### ISSUE TITLE
Invalid state cookie

### ISSUE THREAD

**Issue by span** [ActiveLogin/ActiveLogin.Authentication#298]
**Describe the bug**
Transient errors that say "Invalid state cookie" from the `BankIdHandler`.

This report is from Slack user Anton K:
I can provoke this error myself by removing the “__ActiveLogin.BankIdState”-cookie or by modifying the value within the cookie during the login flow. This got me thinking that some devices/browser may have problems setting the cookie. The cookie is set as HTTP-Only, Secure and Lax. 

**What area is it related to**
BankId

**To Reproduce**
1. Remove “__ActiveLogin.BankIdState” cookie
2. See error

**Expected behavior**
Successful signin.

**Screenshots**
```
[2021-11-29 09:57:57 Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Invalid state cookie
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**NuGet package version**
4.0.0

**Runtime version**
netcoreapp3.1

**Smartphone (please complete the following information):**
 - ios
 - safari

Only seen on ios and safari. Unknown versions.

User reports being able to sign in "sometimes" and then not so it seems to be a transient error where we sometimes get into a bad state. Perhaps due to refresh/reload/back button pressing or using old/stale data.

**Comment by span** [comment]
Not sure why this happens yet.

Best solution is to fix error completely of course but I would not mind a temporary quick fix to at least recover from the error so the user can restart the sign in process.

**Comment by PeterOrneholm** [comment]
Hi @span and thank you for the report!

Can you confirm that you are running in a load balanced scenario with multiple instances?
I JUST realized that the cookie is protected with DataProtection (like how the built-in providers work) and by default Data Protection have one key per server instance.

If this is the case for you, you need to configure a common store for your Data Protections keys:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-6.0#data-protection
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-6.0

If you can confirm this is the case for you, we should definitely add this to our docs.

**Comment by span** [comment]
Hi!Yes we are running in a load balanced environment. We are using azure storage account for our dp keys and it has been working very well for a long time. Sorry 😁On 1 Dec 2021 09:28, Peter Örneholm ***@***.***> wrote:
Hi @span and thank you for the report!
Can you confirm that you are running in a load balanced scenario with multiple instances?
I JUST realized that the cookie is protected with DataProtection (like how the built-in providers work) and by default Data Protection have one key per server instance.
If this is the case for you, you need to configure a common store for your Data Protections keys:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-6.0#data-protection
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-6.0
If you can confirm this is the case for you, we should definitely add this to our docs.

**Comment by antonkallenberg** [comment]
Hi! Thanks for posting the issue here. We're also running in a load balanced environment. We also share DP keys between nodes so unfortunately that's not the issue for us.

**Comment by span** [comment]
Been staring at the code related to this for quite some time now but cannot figure out how it can go wrong. I've been trying all kind of weird login scenarios on ios but cannot reproduce.

I would love some feedback on workarounds.

1. Redirect user back to where they came from and ask them to try again
2. Redirect user back to challenge and start the login scenario again when the cookie value is null

It seems both of these can be solved from outside the library using the event system. Would that be a good idea or is there a preferred way of hooking into the auth flow?

**Comment by antonkallenberg** [comment]
Hi,

We've been locking for the root causes for quite a while now. Right now we have a custom error page where we urge the user to try again by clicking a button to restart the flow. When clicking the button the user get redirected back to the original page.

Below the "try again"-button we've a small contract form, just a text field where the user can enter email/phone number if the error is persistent. We were hoping to find a user which have a device which has a permanent login problem. But as of now all users we talked to seems to be able to login after one och two retries.

We're using Identity Server. The error page is just aspnet core's regular 500-page. The text is general and the application is only used for logins so it's applicable for all login flow errors.

Will keep you updated if we find something new related to this.

**Comment by PeterOrneholm** [comment]
We have been spending some time investing logs and trying to narrow down potential causes. Here are some findings.

Please confirm or deny if these seems correct @antonkallenberg and @span.

- Only mobile devices seem to get this. We have found some that identify as Safari on MacOS, BUT I'm quite certain that these are in fact iPad OS that is (given only the User Agent) impossible to distinguish from Safari on MacOS.
- Both Android and iOS are affected.
- On all the successful logins we found in the logins, the first event being logged is the `AspNetChallangeSuccess`. The flow is so that this should be logged in `BankIdHandler` > `HandleChallengeAsync`.
- On all unsuccessful logins, we found that the `AspNetChallangeSuccess` event was missing.
- Digging deeper - we noticed that on the unsuccessful logins, the user seems to go straight into the "BankID UI" available at: __/BankIdAuthentication/Login__. There are no logs that indicate that the user has been to the page where the authentication challenge is initiated, and therefore the state cookie is never set.

Here are some logs to backup this:
![1_](https://user-images.githubusercontent.com/1662918/146199741-0ce6a0b6-d4ef-4ded-9c18-a2a570fa9048.png)
![2_](https://user-images.githubusercontent.com/1662918/146199745-8b35328b-f6cc-4a8d-a608-3367fda04b1c.png)
![3_](https://user-images.githubusercontent.com/1662918/146199746-8647b11a-b24b-4a2a-bd27-95cf02208472.png)

We have been trying to produce a few ideas on how this can arise:
1. The user bookmarks the page where you login to BankID, and therefore goes straight to this page
2. The user starts entering the URL "example.com" and in the "URL suggestion toolbar" the "Login to Example.com" appears and the user clicks that.
3. The user starts the login flow, waits for long enough time for the cookie to be deleted (it is a session cookie) and then tries to login and the cookie is gone

We know it "should not" be these causes:
- Initiated in one browser but redirected back to another. If this were the case, the __OrderRef__ stored in sessionStorage using JavaScript would be empty and therefore the login flow would be repeated. This would cause the same issue, BUT should also show up as two AuthSuccess in the logs, which I can't see it does.
- When looking at the code, it could have been that the cookie was sent to the server but could have contained an invalid value that could not be decrypted. But according to the ASP.NET Docs, that should throw and error. So, the cookie is either not sent or is empty.
- We did give the [SameSite](https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-6.0) a thought, but everything seems fine there
- We did check if the cookie [became to large](https://docs.devexpress.com/AspNet/11912/common-concepts/cookies-support) and wasn't sent, but this seems highly unlikely. 
- When doing the "challenge" a cookie is set, and the user redirected to __/BankIdAuthentication/Login__. If we had set this as a permanent redirect, it could in theory have been skipped the second time the user clicks login, but it is not a permanent redirect.

I have a strong feeling that it is number 2 above. With the amount of errors we see, all the other options seems to specific to have such large amount of errors.

**Comment by PeterOrneholm** [comment]
We have been spending some time investing logs and trying to narrow down potential causes. Here are some findings.

Please confirm or deny if these seems correct @antonkallenberg and @span.

- Only mobile devices seem to get this. We have found some that identify as Safari on MacOS, BUT I'm quite certain that these are in fact iPad OS that is (given only the User Agent) impossible to distinguish from Safari on MacOS.
- Both Android and iOS are affected.
- On all the successful logins we found in the logins, the first event being logged is the `AspNetChallangeSuccess`. The flow is so that this should be logged in `BankIdHandler` > `HandleChallengeAsync`.
- On all unsuccessful logins, we found that the `AspNetChallangeSuccess` event was missing.
- Digging deeper - we noticed that on the unsuccessful logins, the user seems to go straight into the "BankID UI" available at: __/BankIdAuthentication/Login__. There are no logs that indicate that the user has been to the page where the authentication challenge is initiated, and therefore the state cookie is never set.

We have been trying to produce a few ideas on how this can arise:
- The user bookmarks the page where you login to BankID, and therefore goes straight to this page
- The user starts entering the URL "example.com" and in the "URL suggestion toolbar" the "Login to Example.com" appears and the user clicks that.
- The user starts the login flow, waits for long enough time for the cookie to be deleted (it is a session cookie) and then tries to login and the cookie is gone

Here are some logs to backup this:
![1_](https://user-images.githubusercontent.com/1662918/146199741-0ce6a0b6-d4ef-4ded-9c18-a2a570fa9048.png)
![2_](https://user-images.githubusercontent.com/1662918/146199745-8b35328b-f6cc-4a8d-a608-3367fda04b1c.png)
![3_](https://user-images.githubusercontent.com/1662918/146199746-8647b11a-b24b-4a2a-bd27-95cf02208472.png)


We know it "should not" be these causes:
- Initiated in one browser but redirected back to another. If this were the case, the __OrderRef__ stored in sessionStorage using JavaScript would be empty and therefore the login flow would be repeated. This would cause the same issue, BUT should also show up as two AuthSuccess in the logs, which I can't see it does.
- When looking at the code, it could have been that the cookie was sent to the server but could have contained an invalid value that could not be decrypted. But according to the ASP.NET Docs, that should throw and error. So, the cookie is either not sent or is empty.
- We did give the [SameSite](https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-6.0) a thought, but everything seems fine there
- We did check if the cookie [became to large](https://docs.devexpress.com/AspNet/11912/common-concepts/cookies-support) and wasn't sent, but this seems highly unlikely. 
- When doing the "challenge" a cookie is set, and the user redirected to __/BankIdAuthentication/Login__. If we had set this as a permanent redirect, it could in theory have been skipped the second time the user clicks login, but it is not a permanent redirect.

I have a strong feeling that it is

**Comment by PeterOrneholm** [comment]
> * When looking at the code, it could have been that the cookie was sent to the server but could have contained an invalid value that could not be decrypted. But according to the ASP.NET Docs, that should throw and error. So, the cookie is either not sent or is empty.

I was kind of wrong here. `IDataProtector` will throw an error, but we use that one wrapped in SecureDataFormat (that handles serialization etc) and that one catches all the exceptions:
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Core/src/SecureDataFormat.cs#L89

So, it could potentially be a cookie there - just not correct. But from logs we have seen that the cookie seems to be missing.

**Comment by PeterOrneholm** [comment]
A beta is now released to NuGet - please try it out when you have time!
https://www.nuget.org/packages/ActiveLogin.Authentication.BankId.AspNetCore/4.1.0-beta-1

Ping @span @antonkallenberg

**Comment by antonkallenberg** [comment]
@PeterOrneholm Have created our own IBankIdInvalidStateHandler. Tested in my local development environment, works great! Not deployed to production yet, but it "works on my machine". Great job, thanks!
