### ISSUE TITLE
Support for text on the intention of an identification

### ISSUE THREAD

**Issue by equist** [ActiveLogin/ActiveLogin.Authentication#336]
**Is your feature request related to a problem? Please describe.**
BankId has added support for text on the intention of an identification and this should be exposed by ActiveLogin.

**What area is it related to**
Extend API so it is possible to pass text on the intention of an identification. 

**Describe the solution you'd like**
It would be good to support both as a setting (eas of use for many situation), but I believe it should be able to set the text on a case by case basis too.

**Additional context**
https://www.bankid.com/foretag/avsikt

**Comment by PeterOrneholm** [comment]
Already in the backlog since yesterday ;)
https://github.com/ActiveLogin/ActiveLogin.Authentication/issues/328

I stumbled upon it last night when I checked a thing in the documentation.

Please drop a comment if you have any specific ideas on how you want to set the text. I have written a few ideas in that issue.
