### ISSUE TITLE
Add support for entering custom text on mobile BankId log in screen

### ISSUE THREAD

**Issue by gripenstedt** [ActiveLogin/ActiveLogin.Authentication#395]
Many companies and organisations have added a custom text that is visible when logging in stating something along the lines of "Be aware that we never contact users and tell them to log in. All logins should be on your own initiative".

Would be nice to be able to add such a text.

**Comment by PeterOrneholm** [comment]
I'm glad to tell you that we've had that feature since February (version 5.0.0):
https://github.com/ActiveLogin/ActiveLogin.Authentication/issues/328

See the docs here:
https://github.com/ActiveLogin/ActiveLogin.Authentication/blob/main/docs/articles/bankid.md#resolve-user-data-on-auth-request

Is this what you were looking for? I'll close this issue as already implemented, but if you are lacking something, please let us know!

**Comment by gripenstedt** [comment]
Great! Thanks.
