### ISSUE TITLE
Naming of .AddGrandId()

### ISSUE THREAD

**Issue by PeterOrneholm** [ActiveLogin/ActiveLogin.Authentication#46]
Preparing for supporting SITHS through GrandID (#45) inspired by the PR #44 by @hematmedhelp I realized it might be a good thing to rename the .AddGrandId() method into something more specific for BankID.

BankID and SITHS do share some parts in the underlying API (like name etc) but differs in what other data is returned (Personal Identty number, email etc). Also, concepts like .AddSameDevice() and .AddOtherDeivce() probably differs enough that it should be two implementations, that might (and will) share code under the covers.

I see two potential patterns:

**Pattern 1:**

* `.AddGrandIdBankId()`
* `.AddGrandIdSiths()`

**Pattern 2:**

An alternative would be to keep the top level `.AddGrandId()` but split it further down, like this:

```csharp
services
    .AddAuthentication()
    .AddGrandId(builder =>
    {
        builder
            .UseDevelopmentEnvironment()
            .AddBankIdSameDevice(options => { })
            .AddBankIdOtherDevice(options => { })
            .AddSiths(options => { });
    });
```

Any input or other ideas?

**Comment by PeterOrneholm** [comment]
Would be great with input from @hematmedhelp who wrote the PR and from @fredrik-lundin which I know has worked with SITHS before.

**Comment by Zonnex** [comment]
If Siths is something related to GrandId, then I'd expect it to be part of the builder

**Comment by hematmedhelp** [comment]
@PeterOrneholm 

According to the API-documentation from e-identitet the flows and endpoints for GrandId and Siths are identical - the practical difference that I've found is the reply with the user claims.

In fact Siths will work currently in any of the methods within `AddGrandId()` as long as you change this line:

```
 private IEnumerable<Claim> GetClaims(SessionStateResponse loginResult, DateTimeOffset? expiresUtc)
        {
            // will throw exception due to PersonalIdentityNumber being null
            var personalIdentityNumber = SwedishPersonalIdentityNumber.Parse(loginResult.UserAttributes.PersonalIdentityNumber);
           ...
       }
```

So I'm guessing this discussion is more about the syntax rather than the actual implementation.

Since Siths is part of GrandId I think **Pattern 2** is more representable.

**Comment by hematmedhelp** [comment]
But perhaps **Pattern 2** isn't the most viable. Since the options from the builder might become confusing. Things like `IssueGenderClaim` isn't relevant and won't work since you're not getting a social security number to verify against.

I don't think the rewrites required merits the nicetity of having it in the builder.

**Comment by PeterOrneholm** [comment]
> According to the API-documentation from e-identitet the flows and endpoints for GrandId and Siths are identical - the practical difference that I've found is the reply with the user claims.

Do you by chanse have link to the API docs for GrandID SITHS?

**Comment by PeterOrneholm** [comment]
> But perhaps **Pattern 2** isn't the most viable. Since the options from the builder might become confusing. Things like `IssueGenderClaim` isn't relevant and won't work since you're not getting a social security number to verify against.

Both of them would allow us to have different options. `.AddSiths()` could have another set of options not including `IssueGenderClaim` for example.

How does SITHS work, is `.AddSameDevice()` and `.AddOtherDevice()` relevant or is it always one or the other, so that `.AddSiths()` is the only available option?

**Comment by nikolaykrondev** [comment]
Would also vote for the option 2

**Comment by hematmedhelp** [comment]
> > According to the API-documentation from e-identitet the flows and endpoints for GrandId and Siths are identical - the practical difference that I've found is the reply with the user claims.
> 
> Do you by chanse have link to the API docs for GrandID SITHS?

Not a direct link, they were included in an email. See attached below.
[GrandID API - SITHS developer documentation.pdf](https://github.com/ActiveLogin/ActiveLogin.Authentication/files/2639452/GrandID.API.-.SITHS.developer.documentation.pdf)

> > But perhaps **Pattern 2** isn't the most viable. Since the options from the builder might become confusing. Things like `IssueGenderClaim` isn't relevant and won't work since you're not getting a social security number to verify against.
> 
> Both of them would allow us to have different options. `.AddSiths()` could have another set of options not including `IssueGenderClaim` for example.
> 
> How does SITHS work, is `.AddSameDevice()` and `.AddOtherDevice()` relevant or is it always one or the other, so that `.AddSiths()` is the only available option?

I did try to quickly much about with the source to see if `AddSiths()` could be quickly be done but I ran into having to duplicate code - since the registered authentication handler only accepts `GrandIdAuthenticationOptions `and so does `AddScheme `. Sounds like you've already got something in mind though.

I can email my contact at e-identitet and ask for clarification since I can't find a definitive answer in the documentation. I would guess that there are in fact two endpoints, one for the native app custom protocol and one for the "normal" https. But since the flow appears to be identical in either scenario I think just `AddSiths()` will suffice. 

Should there be two difference "endpoints" or services, and one needed to support both in the same IdentityServer or provider you could just chain the methods.

```
.AddSiths("desktop-scheme", "SITHS Desktop", opts => 
{
 opts.GrandIdAuthenticateServiceKey = configuration.GetValue<string>("Settings:FirstKey");
})
.AddSiths("mobile-scheme", "SITHS Native" opts => 
{
 opts.GrandIdAuthenticateServiceKey = configuration.GetValue<string>("Settings:SecondKey");
});
```

**Comment by PeterOrneholm** [comment]
Thank you for the docs @hematmedhelp! Form reading the docs, do I get it right that you have two keys, one for mobile and one for desktop that you have received from Svensk E-identitet?

I've now read it through and the pattern looks almost the same as for BankID. But it differs in the way that for BankID it's more "on this device" or "on another device", while SITHS explicitly says "on desktop" or "on mobile". I'm not sure whether we are expected to figure that out and choose the appropriate key (mobile/desktop) or present both options to the user. It would make sense to figure it our and simplify the choise for the user.

Anyhow, let's continue the SITHS discussion in #45, before 1.0.0 release we need to rename our current methods to include BankId, like this:

```csharp
services
    .AddAuthentication()
    .AddGrandId(builder =>
    {
        builder
            .UseDevelopmentEnvironment()
            .AddBankIdSameDevice(options => { })
            .AddBankIdOtherDevice(options => { });
    });
```

Not only does it make most sense given how GrandId works, but also with the current technical implementation we can only have one ApiKey from GrandId (it's injected into the API wrapper). I'll make a PR to reflect this change and start writing on the proposed implementation in the other issue.

**Comment by PeterOrneholm** [comment]
Renamed in #47
